package Interfaz;

import Fuentes.ListaProfesores;
import Fuentes.Fecha;
import Fuentes.ProfesorTitular;
import Fuentes.ProfesorContrato;

public class JFProfesores extends javax.swing.JFrame {
    
    public  ListaProfesores lista;
    public JFProfesores() {
        initComponents();
        lista = new ListaProfesores();
        this.setLocationRelativeTo(null);
        this.jTAListaProfesores.setEditable(false);
        this.jTAProfesoresTitulares.setEditable(false);
        this.jTAProfesoresContrato.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTFNombresProTitular = new javax.swing.JTextField();
        jTFFechaNacimientoProTitular = new javax.swing.JTextField();
        jTFExperienciaProTitular = new javax.swing.JTextField();
        jTFFechaIngresoProTitular = new javax.swing.JTextField();
        jTFFechaNombramientoProTitular = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAProfesoresTitulares = new javax.swing.JTextArea();
        jTFNumHorasInvestigacionProTitular = new javax.swing.JTextField();
        jTFNumHorasClaseProTitular = new javax.swing.JTextField();
        jTFCostoHorasProTitular = new javax.swing.JTextField();
        jBAceptarProTitular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTFNombresProContrato = new javax.swing.JTextField();
        jTFFechaNacimientoProContrato = new javax.swing.JTextField();
        jTFExperienciaDocenciaProContrato = new javax.swing.JTextField();
        jTFFechaIngresoProContrato = new javax.swing.JTextField();
        jTFFechaFinalContratoProContrato = new javax.swing.JTextField();
        jTFNumHorasClaseProContrato = new javax.swing.JTextField();
        jTFCostoHorasProContrato = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAProfesoresContrato = new javax.swing.JTextArea();
        jBAceptarPorContaro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAListaProfesores = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuSalir = new javax.swing.JMenuItem();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nombres:");

        jLabel3.setText("Fecha de Nacimiento:");

        jLabel4.setText("dd/mm/aaaa");

        jLabel5.setText("Fecha de Ingreso: ");

        jLabel6.setText("dd/mm/aaaa");

        jLabel7.setText("Fecha de Nombramiento:");

        jLabel8.setText("dd/mm/aaaa");

        jLabel9.setText("Número de Horas de Investigación:");

        jLabel10.setText("Experiencia en Docencia:");

        jLabel11.setText("Número de Horas de Clase:");

        jLabel12.setText("Costo Horas:");

        jTFNombresProTitular.setBackground(new java.awt.Color(255, 255, 255));
        jTFNombresProTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombresProTitularActionPerformed(evt);
            }
        });

        jTFFechaNacimientoProTitular.setBackground(new java.awt.Color(255, 255, 255));
        jTFFechaNacimientoProTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFechaNacimientoProTitularActionPerformed(evt);
            }
        });

        jTFExperienciaProTitular.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaIngresoProTitular.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaNombramientoProTitular.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Profesores Titulares:");

        jTAProfesoresTitulares.setBackground(new java.awt.Color(255, 255, 255));
        jTAProfesoresTitulares.setColumns(20);
        jTAProfesoresTitulares.setRows(5);
        jScrollPane3.setViewportView(jTAProfesoresTitulares);

        jTFNumHorasInvestigacionProTitular.setBackground(new java.awt.Color(255, 255, 255));

        jTFNumHorasClaseProTitular.setBackground(new java.awt.Color(255, 255, 255));

        jTFCostoHorasProTitular.setBackground(new java.awt.Color(255, 255, 255));

        jBAceptarProTitular.setText("Aceptar");
        jBAceptarProTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarProTitularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNombresProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTFFechaNacimientoProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFFechaNombramientoProTitular))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFExperienciaProTitular)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTFFechaIngresoProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(130, 130, 130)
                        .addComponent(jTFCostoHorasProTitular))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFNumHorasClaseProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTFNumHorasInvestigacionProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAceptarProTitular))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNombresProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFFechaNacimientoProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTFExperienciaProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFFechaIngresoProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTFFechaNombramientoProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTFNumHorasInvestigacionProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTFNumHorasClaseProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jBAceptarProTitular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTFCostoHorasProTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ProfesorTitular", jPanel1);

        jLabel14.setText("Nombres:");

        jLabel15.setText("Fecha de Nacimiento:");

        jLabel16.setText("dd/mm/aaaa");

        jLabel17.setText("Experiencia en Docencia:");

        jLabel18.setText("Fecha de Ingreso:");

        jLabel19.setText("dd/mm/aaaa");

        jLabel20.setText("Fecha de Finalización de Contrato:");

        jLabel21.setText("dd/mm/aaaa");

        jLabel22.setText("Número de Horas de Clase:");

        jLabel23.setText("Costo de Horas:");

        jTFNombresProContrato.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaNacimientoProContrato.setBackground(new java.awt.Color(255, 255, 255));

        jTFExperienciaDocenciaProContrato.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaIngresoProContrato.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaFinalContratoProContrato.setBackground(new java.awt.Color(255, 255, 255));

        jTFNumHorasClaseProContrato.setBackground(new java.awt.Color(255, 255, 255));

        jTFCostoHorasProContrato.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setText("Profesores por Contrato:");

        jTAProfesoresContrato.setBackground(new java.awt.Color(255, 255, 255));
        jTAProfesoresContrato.setColumns(20);
        jTAProfesoresContrato.setRows(5);
        jScrollPane4.setViewportView(jTAProfesoresContrato);

        jBAceptarPorContaro.setText("Aceptar");
        jBAceptarPorContaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarPorContaroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(73, 73, 73)
                            .addComponent(jTFNombresProContrato))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFFechaNacimientoProContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel16)
                        .addComponent(jLabel21)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFExperienciaDocenciaProContrato)
                                .addComponent(jTFFechaIngresoProContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addGap(44, 44, 44)
                            .addComponent(jTFNumHorasClaseProContrato))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(108, 108, 108)
                            .addComponent(jTFCostoHorasProContrato)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFFechaFinalContratoProContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAceptarPorContaro))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTFNombresProContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTFFechaNacimientoProContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTFExperienciaDocenciaProContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jTFFechaFinalContratoProContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jTFNumHorasClaseProContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTFFechaIngresoProContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jBAceptarPorContaro))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCostoHorasProContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ProfesorContrato", jPanel2);

        jLabel1.setText("Lista Profesores:");

        jTAListaProfesores.setBackground(new java.awt.Color(255, 255, 255));
        jTAListaProfesores.setColumns(20);
        jTAListaProfesores.setRows(5);
        jScrollPane1.setViewportView(jTAListaProfesores);

        jMenu1.setText("File");

        jMnuSalir.setText("Salir");
        jMnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFFechaNacimientoProTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFechaNacimientoProTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFechaNacimientoProTitularActionPerformed

    private void jTFNombresProTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombresProTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombresProTitularActionPerformed

    private void jBAceptarPorContaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarPorContaroActionPerformed
        Fecha fechaNacimiento = new Fecha(this.jTFFechaNacimientoProContrato.getText());
        Fecha fechaIngreso = new Fecha(this.jTFFechaIngresoProContrato.getText());
        Fecha fechaExpedicionContrato = new Fecha(this.jTFFechaFinalContratoProContrato.getText());
        String nombres = this.jTFNombresProContrato.getText();
        int numHorasClase = Integer.parseInt(this.jTFNumHorasClaseProContrato.getText());
        double costoHoras = Double.parseDouble(this.jTFCostoHorasProContrato.getText());
        String experienciaDocencia = this.jTFExperienciaDocenciaProContrato.getText();
        ProfesorContrato profesorContrato = new ProfesorContrato(fechaExpedicionContrato,costoHoras,numHorasClase,experienciaDocencia,fechaIngreso,nombres,fechaNacimiento);
        this.jTAProfesoresContrato.setText(profesorContrato.toString());
        lista.addProfesor(profesorContrato);
        this.jTAListaProfesores.setText(lista.toString());
    }//GEN-LAST:event_jBAceptarPorContaroActionPerformed

    private void jMnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnuSalirActionPerformed

    private void jBAceptarProTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarProTitularActionPerformed
        Fecha fechaNacimiento = new Fecha(this.jTFFechaNacimientoProTitular.getText());
        Fecha fechaIngreso = new Fecha(this.jTFFechaIngresoProTitular.getText());
        String nombres = this.jTFNombresProTitular.getText();
        int numHorasClase = Integer.parseInt(this.jTFNumHorasClaseProTitular.getText());
        double costoHoras = Double.parseDouble(this.jTFCostoHorasProTitular.getText());
        String experienciaDocencia = this.jTFExperienciaProTitular.getText();
        Fecha fechaNombramiento = new Fecha(this.jTFFechaNombramientoProTitular.getText());
        int numHorasInvestigacion = Integer.parseInt(this.jTFNumHorasInvestigacionProTitular.getText());
        ProfesorTitular profesorTitular = new ProfesorTitular(fechaNombramiento,numHorasInvestigacion,numHorasClase,costoHoras,experienciaDocencia,fechaIngreso,nombres,fechaNacimiento);
        this.jTAProfesoresTitulares.setText(profesorTitular.toString());
        lista.addProfesor(profesorTitular);
        this.jTAListaProfesores.setText(lista.toString());
    }//GEN-LAST:event_jBAceptarProTitularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFProfesores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarPorContaro;
    private javax.swing.JButton jBAceptarProTitular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTAListaProfesores;
    private javax.swing.JTextArea jTAProfesoresContrato;
    private javax.swing.JTextArea jTAProfesoresTitulares;
    private javax.swing.JTextField jTFCostoHorasProContrato;
    private javax.swing.JTextField jTFCostoHorasProTitular;
    private javax.swing.JTextField jTFExperienciaDocenciaProContrato;
    private javax.swing.JTextField jTFExperienciaProTitular;
    private javax.swing.JTextField jTFFechaFinalContratoProContrato;
    private javax.swing.JTextField jTFFechaIngresoProContrato;
    private javax.swing.JTextField jTFFechaIngresoProTitular;
    private javax.swing.JTextField jTFFechaNacimientoProContrato;
    private javax.swing.JTextField jTFFechaNacimientoProTitular;
    private javax.swing.JTextField jTFFechaNombramientoProTitular;
    private javax.swing.JTextField jTFNombresProContrato;
    private javax.swing.JTextField jTFNombresProTitular;
    private javax.swing.JTextField jTFNumHorasClaseProContrato;
    private javax.swing.JTextField jTFNumHorasClaseProTitular;
    private javax.swing.JTextField jTFNumHorasInvestigacionProTitular;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
