/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Fuentes.Vector;
import javax.swing.JOptionPane;

public class JFVector extends javax.swing.JFrame {

   private Vector vector;
   private String salida;
    
    public JFVector() {
        initComponents();
        this.setLocationRelativeTo(null);
        jCBOperaciones.setVisible(false); //ocultar el combo de operaciones
        this.jBAceptar.setVisible(false); //ocultar botón Aceptar hasta que ingrese la dimensión
        salida="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFDimension = new javax.swing.JTextField();
        jBAceptar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAResultados = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jBNuevo = new javax.swing.JButton();
        jCBOperaciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DIMENSIÓN");

        jTFDimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDimensionActionPerformed(evt);
            }
        });

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jTAResultados.setColumns(20);
        jTAResultados.setRows(5);
        jScrollPane1.setViewportView(jTAResultados);

        jLabel2.setText("RESULTADOS");

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jCBOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sumatoria de Elementos", "Sumatoria de números primos", "Contar números perfectos", "Clasificar el vector", "Buscar el Número mayor", "Búsqueda Binaria", "Clase Arrays: Clasificar el vector", "Clase Arrays: Búsqueda binaria", "Clase Arrays: Buscar el mayor" }));
        jCBOperaciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBOperacionesItemStateChanged(evt);
            }
        });
        jCBOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBOperacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBNuevo)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(jTFDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBAceptar)
                                    .addGap(27, 27, 27)
                                    .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCBOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBAceptar))
                .addGap(18, 18, 18)
                .addComponent(jBNuevo)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDimensionActionPerformed
        this.jBAceptar.setVisible(true); //se activa el botón cuanbdo se ingresa otra dimensión
        
        this.jTAResultados.setText("");
        this.jTFDimension.requestFocus();
            jCBOperaciones.setVisible(true); //mostrar el combo de operaciones
    }//GEN-LAST:event_jTFDimensionActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        this.jTFDimension.requestFocus(); //Focus a la caja de ingreso de datos
        vector = new Vector(Integer.parseInt(this.jTFDimension.getText()));
        vector.setVector();
        salida+= vector.toString();
        this.jTAResultados.setText(salida);
        this.jCBOperaciones.setVisible(true);
        
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        this.jTFDimension.setText("");
        this.jTAResultados.setText("");
        this.jTFDimension.requestFocus();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jCBOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBOperacionesActionPerformed
        switch(jCBOperaciones.getSelectedIndex()) {
            case 0: 
            {
                salida+= "\n Suma de Elementos: " + vector.sumarElementos();
                this.jTAResultados.setText(salida);
                break;
            }
            case 1: 
            {
               salida+="\n Suma de Primos: " + vector.sumarPrimos();
               this.jTAResultados.setText(salida);
               break;
            }
            case 2:
            {
                salida+= "\n Numero de números Perfectos:" + vector.detectarNPerfectos();
                this.jTAResultados.setText(salida);
                break;
            }
            case 3:
            {
                vector.ordenarVector();
                salida += "\n El vector ordenado es:" + vector.toString();
                this.jTAResultados.setText(salida);
                break;
            }
            case 4:
            {
                salida += "\n El numero mayor del vector es:" + vector.calcularNumeroMayor();
                this.jTAResultados.setText(salida);
                break;
            }
            case 5:
            {
                String x = JOptionPane.showInputDialog("Ingrese el elemento de la matriz para encontar su índice");
                int valorIngresado = Integer.parseInt(x);
                
                int dimensionXD = Integer.parseInt(this.jTFDimension.getText());
                int indice = vector.busquedaBinaria(0, dimensionXD - 1 ,valorIngresado);
                salida += "\n El elemento esta en el índice:" + indice;
                this.jTAResultados.setText(salida);
                break;
            }
            case 6: 
            {
             vector.clasificarArray();
             salida+= "\n Clasificación del vector mediante la clase Array:" + vector.toString();
             this.jTAResultados.setText(salida);
             break;
            }
            case 7:
            {
               String x = JOptionPane.showInputDialog("Ingrese el elemento de la matriz para encontar su índice");
               int valorIngresado = Integer.parseInt(x);
               vector.ordenarVector();
               long sven = vector.busquedaBinariaArray(valorIngresado);
               salida += "\n El elemento esta en el índice:" + sven ;
               this.jTAResultados.setText(salida);
               break;  
            }
            case 8: 
            {
                salida += "\n El numero mayor del vector utilizando la clase array es:" + vector.conocerNumeroMayorArray();
                this.jTAResultados.setText(salida);
                break;
            }
        }
    }//GEN-LAST:event_jCBOperacionesActionPerformed

    private void jCBOperacionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBOperacionesItemStateChanged
        
    }//GEN-LAST:event_jCBOperacionesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBOperaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAResultados;
    private javax.swing.JTextField jTFDimension;
    // End of variables declaration//GEN-END:variables
}
