package Interfaces;

import Fuentes.EmpleadoAsalariado;
import Fuentes.EmpleadoBaseMasComision;
import Fuentes.EmpleadoPorComision;
import Fuentes.EmpleadoPorHoras;
import Fuentes.Fecha;
import Fuentes.ListaEmpleadosLink;

public class JFEmpleados extends javax.swing.JFrame {
    public ListaEmpleadosLink lista;

    public JFEmpleados() {
        initComponents();
        lista = new ListaEmpleadosLink();
        this.setLocationRelativeTo(null); 
        this.jTAListaEmpleados.setEditable(false);
        this.jTAEmpleadoAsalariado.setEditable(false);
        this.jTAEmpleadoBaseMasComision.setEditable(false);
        this.jTAEmpleadoPorHoras.setEditable(false);
        this.jTAEmpleadoPorComision.setEditable(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTFNombresAsalariado = new javax.swing.JTextField();
        jTFFechaNacimientoAsalariado = new javax.swing.JTextField();
        jTFFechaIngresoAsalariado = new javax.swing.JTextField();
        jTFSalarioBasicoAsalariado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAEmpleadoAsalariado = new javax.swing.JTextArea();
        jBAceptarAsalariado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTFNombresPorHoras = new javax.swing.JTextField();
        jTFFechaNacimientoPorHoras = new javax.swing.JTextField();
        jTFFechaIngresoPorHoras = new javax.swing.JTextField();
        jTFNumeroHorasPorHoras = new javax.swing.JTextField();
        jTFCostoHorasPorHoras = new javax.swing.JTextField();
        jBAceptarPorHoras = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTAEmpleadoPorHoras = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTFNombresPorComision = new javax.swing.JTextField();
        jTFFechaNacimientoPorComision = new javax.swing.JTextField();
        jTFFechaIngresoPorComision = new javax.swing.JTextField();
        jTFVentaTotalPorComision = new javax.swing.JTextField();
        jTFValorRecibirPorComision = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTAEmpleadoPorComision = new javax.swing.JTextArea();
        jBAceptarPorComision = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFNombresBasesMasComision = new javax.swing.JTextField();
        jTFFechaNacimientoBasesMasComision = new javax.swing.JTextField();
        jTFFechaIngresoBasesMasComision = new javax.swing.JTextField();
        jTFSalarioBasesMasComision = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFTotalVendidoBasesMasComision = new javax.swing.JTextField();
        jTFPagarBasesMasComision = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAEmpleadoBaseMasComision = new javax.swing.JTextArea();
        jBAcpetarBasesMasComision = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAListaEmpleados = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados\n");

        jLabel11.setText("Nombres:");

        jLabel12.setText("Fecha de Nacimiento:");

        jLabel13.setText("dd/mm/aaaa");

        jLabel14.setText("Fecha de Ingreso:");

        jLabel15.setText("dd/mm/aaaa");

        jLabel16.setText("Salario Básico:");

        jTFNombresAsalariado.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaNacimientoAsalariado.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaIngresoAsalariado.setBackground(new java.awt.Color(255, 255, 255));

        jTFSalarioBasicoAsalariado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Empleado Asalariado:");

        jTAEmpleadoAsalariado.setBackground(new java.awt.Color(255, 255, 255));
        jTAEmpleadoAsalariado.setColumns(20);
        jTAEmpleadoAsalariado.setRows(5);
        jScrollPane3.setViewportView(jTAEmpleadoAsalariado);

        jBAceptarAsalariado.setText("Acpetar");
        jBAceptarAsalariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarAsalariadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(79, 79, 79)
                        .addComponent(jTFNombresAsalariado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAceptarAsalariado)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFFechaNacimientoAsalariado)
                                .addComponent(jTFFechaIngresoAsalariado)
                                .addComponent(jTFSalarioBasicoAsalariado)))))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFNombresAsalariado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTFFechaNacimientoAsalariado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTFFechaIngresoAsalariado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTFSalarioBasicoAsalariado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBAceptarAsalariado)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asalariado", jPanel2);

        jLabel19.setText("Nombres:");

        jLabel20.setText("Fecha de Nacimiento:");

        jLabel21.setText("dd/mm/aaaa");

        jLabel22.setText("Fecha de Ingreso:");

        jLabel23.setText("dd/mm/aaaa");

        jLabel24.setText("Número de Horas:");

        jTFNombresPorHoras.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaNacimientoPorHoras.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaIngresoPorHoras.setBackground(new java.awt.Color(255, 255, 255));

        jTFNumeroHorasPorHoras.setBackground(new java.awt.Color(255, 255, 255));

        jTFCostoHorasPorHoras.setBackground(new java.awt.Color(255, 255, 255));

        jBAceptarPorHoras.setText("Aceptar");
        jBAceptarPorHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarPorHorasActionPerformed(evt);
            }
        });

        jLabel26.setText("Empleados por Horas:");

        jTAEmpleadoPorHoras.setBackground(new java.awt.Color(255, 255, 255));
        jTAEmpleadoPorHoras.setColumns(20);
        jTAEmpleadoPorHoras.setRows(5);
        jScrollPane6.setViewportView(jTAEmpleadoPorHoras);

        jLabel27.setText("Costo de Horas:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(75, 75, 75)
                        .addComponent(jTFNombresPorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAceptarPorHoras)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFCostoHorasPorHoras)
                                .addComponent(jTFFechaIngresoPorHoras)
                                .addComponent(jTFNumeroHorasPorHoras)
                                .addComponent(jTFFechaNacimientoPorHoras, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTFNombresPorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))
                            .addComponent(jTFFechaNacimientoPorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTFFechaIngresoPorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTFNumeroHorasPorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCostoHorasPorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)))
                    .addComponent(jScrollPane6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAceptarPorHoras)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Por Horas", jPanel3);

        jLabel28.setText("Nombres:");

        jLabel29.setText("Fecha de Nacimiento:");

        jLabel30.setText("dd/mm/aaaa");

        jLabel31.setText("Fecha de Ingreso:");

        jLabel32.setText("dd/mm/aaaa");

        jLabel33.setText("Venta Total:");

        jLabel34.setText("% que a Recibir:");

        jTFNombresPorComision.setBackground(new java.awt.Color(255, 255, 255));
        jTFNombresPorComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombresPorComisionActionPerformed(evt);
            }
        });

        jTFFechaNacimientoPorComision.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaIngresoPorComision.setBackground(new java.awt.Color(255, 255, 255));

        jTFVentaTotalPorComision.setBackground(new java.awt.Color(255, 255, 255));

        jTFValorRecibirPorComision.setBackground(new java.awt.Color(255, 255, 255));

        jLabel35.setText("Empleado por Comisión:");

        jTAEmpleadoPorComision.setBackground(new java.awt.Color(255, 255, 255));
        jTAEmpleadoPorComision.setColumns(20);
        jTAEmpleadoPorComision.setRows(5);
        jScrollPane7.setViewportView(jTAEmpleadoPorComision);

        jBAceptarPorComision.setText("Aceptar");
        jBAceptarPorComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarPorComisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(71, 71, 71)
                        .addComponent(jTFNombresPorComision, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFFechaNacimientoPorComision)
                            .addComponent(jTFFechaIngresoPorComision)
                            .addComponent(jTFVentaTotalPorComision)
                            .addComponent(jTFValorRecibirPorComision))))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAceptarPorComision))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTFNombresPorComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jTFFechaNacimientoPorComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jTFFechaIngresoPorComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jTFVentaTotalPorComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jTFValorRecibirPorComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAceptarPorComision))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Por Comisión", jPanel4);

        jLabel1.setText("Nombres:");

        jLabel2.setText("Fecha de Nacimiento: ");

        jLabel3.setText("dd/mm/aaaa");

        jLabel4.setText("Fecha de Ingreso:");

        jLabel5.setText("dd/mm/aaaa");

        jLabel6.setText("Salario Básico:");

        jTFNombresBasesMasComision.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaNacimientoBasesMasComision.setBackground(new java.awt.Color(255, 255, 255));

        jTFFechaIngresoBasesMasComision.setBackground(new java.awt.Color(255, 255, 255));

        jTFSalarioBasesMasComision.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Empleado Base Mas Comisión:");

        jLabel8.setText("Total Vendido:");

        jLabel9.setText("% a Pagar:");

        jTFTotalVendidoBasesMasComision.setBackground(new java.awt.Color(255, 255, 255));

        jTFPagarBasesMasComision.setBackground(new java.awt.Color(255, 255, 255));

        jTAEmpleadoBaseMasComision.setBackground(new java.awt.Color(255, 255, 255));
        jTAEmpleadoBaseMasComision.setColumns(20);
        jTAEmpleadoBaseMasComision.setRows(5);
        jScrollPane1.setViewportView(jTAEmpleadoBaseMasComision);

        jBAcpetarBasesMasComision.setText("Acpetar");
        jBAcpetarBasesMasComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAcpetarBasesMasComisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73)
                        .addComponent(jTFNombresBasesMasComision, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFFechaNacimientoBasesMasComision)
                            .addComponent(jTFFechaIngresoBasesMasComision)
                            .addComponent(jTFSalarioBasesMasComision)
                            .addComponent(jTFTotalVendidoBasesMasComision)
                            .addComponent(jTFPagarBasesMasComision))))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAcpetarBasesMasComision))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFNombresBasesMasComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFFechaNacimientoBasesMasComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFFechaIngresoBasesMasComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTFSalarioBasesMasComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTFTotalVendidoBasesMasComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFPagarBasesMasComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAcpetarBasesMasComision))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bases mas Comisión", jPanel5);

        jTAListaEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        jTAListaEmpleados.setColumns(20);
        jTAListaEmpleados.setRows(5);
        jScrollPane2.setViewportView(jTAListaEmpleados);

        jLabel10.setText("Lista Empleados:");

        jMenu1.setText("Opciones");

        jMnuSalir.setText("Salir");
        jMnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuSalir);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarAsalariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarAsalariadoActionPerformed
        Fecha fechaNacimiento = new Fecha(this.jTFFechaNacimientoAsalariado.getText());
        Fecha fechaIngreso = new Fecha(this.jTFFechaIngresoAsalariado.getText());
        double salario= Double.parseDouble(this.jTFSalarioBasicoAsalariado.getText());
        String nombres = this.jTFNombresAsalariado.getText();
        EmpleadoAsalariado empAsa = new EmpleadoAsalariado(salario,fechaIngreso ,nombres, fechaNacimiento);
        this.jTAEmpleadoAsalariado.setText(empAsa.toString());
        lista.addEmpleado(empAsa);
        this.jTAListaEmpleados.setText(lista.toString());
    }//GEN-LAST:event_jBAceptarAsalariadoActionPerformed

    private void jBAcpetarBasesMasComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAcpetarBasesMasComisionActionPerformed
        Fecha fechaNacimiento = new Fecha(this.jTFFechaNacimientoBasesMasComision.getText());
        Fecha fechaIngreso = new Fecha(this.jTFFechaIngresoBasesMasComision.getText());
        String nombres = this.jTFNombresBasesMasComision.getText();
        double totalVenta = Double.parseDouble(this.jTFTotalVendidoBasesMasComision.getText());
        double porcentajePagar = Double.parseDouble(this.jTFPagarBasesMasComision.getText());
        double salario= Double.parseDouble(this.jTFSalarioBasesMasComision.getText());
        EmpleadoBaseMasComision empBaseMasComision = new EmpleadoBaseMasComision(salario,totalVenta,porcentajePagar,fechaIngreso,nombres,fechaNacimiento);
        this.jTAEmpleadoBaseMasComision.setText(empBaseMasComision.toString());
        lista.addEmpleado(empBaseMasComision);
        this.jTAListaEmpleados.setText(lista.toString());   
    }//GEN-LAST:event_jBAcpetarBasesMasComisionActionPerformed

    private void jMnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnuSalirActionPerformed

    private void jBAceptarPorHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarPorHorasActionPerformed
        Fecha fechaNacimiento = new Fecha(this.jTFFechaNacimientoPorHoras.getText());
        Fecha fechaIngreso = new Fecha(this.jTFFechaIngresoPorHoras.getText());
        String nombres = this.jTFNombresPorHoras.getText();
        int numHoras = Integer.parseInt(this.jTFNumeroHorasPorHoras.getText());
        double costoHoras = Double.parseDouble(this.jTFCostoHorasPorHoras.getText());
        EmpleadoPorHoras empPorHoras = new EmpleadoPorHoras(numHoras, costoHoras, fechaIngreso,nombres, fechaNacimiento);
        this.jTAEmpleadoPorHoras.setText(empPorHoras.toString());
        lista.addEmpleado(empPorHoras);
        this.jTAListaEmpleados.setText(lista.toString());
    }//GEN-LAST:event_jBAceptarPorHorasActionPerformed

    private void jBAceptarPorComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarPorComisionActionPerformed
        Fecha fechaNacimiento = new Fecha(this.jTFFechaNacimientoPorComision.getText());
        Fecha fechaIngreso = new Fecha(this.jTFFechaIngresoPorComision.getText());
        String nombres = this.jTFNombresPorComision.getText();
        double totalVenta = Double.parseDouble(this.jTFVentaTotalPorComision.getText());
        double porcentajeComision = Double.parseDouble(this.jTFValorRecibirPorComision.getText());
        EmpleadoPorComision empPorComision = new EmpleadoPorComision(totalVenta, porcentajeComision, fechaIngreso, nombres, fechaNacimiento);
        this.jTAEmpleadoPorComision.setText(empPorComision.toString());
        lista.addEmpleado(empPorComision);
        this.jTAListaEmpleados.setText(lista.toString());
    }//GEN-LAST:event_jBAceptarPorComisionActionPerformed

    private void jTFNombresPorComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombresPorComisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombresPorComisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarAsalariado;
    private javax.swing.JButton jBAceptarPorComision;
    private javax.swing.JButton jBAceptarPorHoras;
    private javax.swing.JButton jBAcpetarBasesMasComision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTAEmpleadoAsalariado;
    private javax.swing.JTextArea jTAEmpleadoBaseMasComision;
    private javax.swing.JTextArea jTAEmpleadoPorComision;
    private javax.swing.JTextArea jTAEmpleadoPorHoras;
    private javax.swing.JTextArea jTAListaEmpleados;
    private javax.swing.JTextField jTFCostoHorasPorHoras;
    private javax.swing.JTextField jTFFechaIngresoAsalariado;
    private javax.swing.JTextField jTFFechaIngresoBasesMasComision;
    private javax.swing.JTextField jTFFechaIngresoPorComision;
    private javax.swing.JTextField jTFFechaIngresoPorHoras;
    private javax.swing.JTextField jTFFechaNacimientoAsalariado;
    private javax.swing.JTextField jTFFechaNacimientoBasesMasComision;
    private javax.swing.JTextField jTFFechaNacimientoPorComision;
    private javax.swing.JTextField jTFFechaNacimientoPorHoras;
    private javax.swing.JTextField jTFNombresAsalariado;
    private javax.swing.JTextField jTFNombresBasesMasComision;
    private javax.swing.JTextField jTFNombresPorComision;
    private javax.swing.JTextField jTFNombresPorHoras;
    private javax.swing.JTextField jTFNumeroHorasPorHoras;
    private javax.swing.JTextField jTFPagarBasesMasComision;
    private javax.swing.JTextField jTFSalarioBasesMasComision;
    private javax.swing.JTextField jTFSalarioBasicoAsalariado;
    private javax.swing.JTextField jTFTotalVendidoBasesMasComision;
    private javax.swing.JTextField jTFValorRecibirPorComision;
    private javax.swing.JTextField jTFVentaTotalPorComision;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
